baseurl = "https://surajmandalcell.github.io/blog"
languageCode = "en"
title = "Blog"
theme = "Hucore"
publishDir = "docs"
copyright = "&copy; 2017 | Follow on <a href=\"https://twitter.com/cruelplatypus67\" target=\"_blank\">Twitter</a>"
disqusShortname = "cruelplatypus67"
# googleAnalytics = ""

[taxonomies]
tag = "blog,surajmandalcell,surajmandal"
category = "blog,content,personal"

[params]
description = "My blog"
keywords = ["blog", "content", "personal"]
author = "Suraj Mandal"
sharingicons = true
displayauthor = true

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/surajmandalcell"
fa_icon = "fa-github"

[[params.social]]
url = "https://gitlab.com/surajmandalcell"
fa_icon = "fa-gitlab"

[[params.social]]
url = "https://twitter.com/cruelplatypus67"
fa_icon = "fa-twitter"

[[params.social]]
url = "https://linkedin.com/in/surajmandalcell"
fa_icon = "fa-linkedin-square"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

[[params.socialshare]]
url = "https://linkedin.com/in/surajmandalcell"
fa_icon = "fa-linkedin-square"